name = "sry-worker"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "RL"
id = "9217c59571364298bba6ce7e0865f6ef"
preview_id = "36cadac2d46740819456833fa257a37f"

[vars]
LLM_KILL_SWITCH = "false"
DEFAULT_MODEL = "workers-ai"
